#!/bin/bash
java -cp bin simulateur.Simulateur -mess 10
java -cp bin simulateur.Simulateur -seed 3 -form NRZ
java -cp bin simulateur.Simulateur -mess 10 -seed 3
java -cp bin simulateur.Simulateur -mess 1010101010101
